name: Daily Learning Updates

on:
  workflow_dispatch:
  schedule:
   - cron: '3 5 * * *'

permissions:
  contents: write

jobs:
  update-learning:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Configure Git
        run: |
          git config user.name "Yashwant Nishad"
          git config user.email "yashwantbit@gmail.com"

      - name: Run update notes
        run: python update_notes.py

      - name: Commit & Push
        run: |
          git add daily_log.txt
          git commit -m "Update daily learning log" || echo "No changes"
          git push origin main
