name: Daily Learning Updates

on:
  workflow_dispatch:
  schedule:
    - cron: '40 18 * * *'   # 12:10 AM IST

permissions:
  contents: write

jobs:
  update-learning:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "Yashwant Nishad"
          git config user.email "yashwantbit@gmail.com"

      - name: Force daily update
        run: |
          echo "Last update (UTC): $(date -u)" >> daily_log.txt

      - name: Commit & Push
        run: |
          git add .
          git commit -m "Daily learning update $(date -u)" || echo "No changes"
          git push origin main
